import { Poppins } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import Mini from './components/Mini'
import Sidebar from './components/Sidebar'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '600',]
})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return ( 
    <html lang="en">
      <body className={poppins.className} >
        <div className="w-screen h-full">
          <div className="p-2">
          <Header/>
          </div>


          <div className="flex w-full h-full  ">

          <div className="w-1/12  shadow-md bg-white p-2">
          <Sidebar/>
          </div>

          <div className="w-8/12 p-2">
          {children}
          </div>

          <div className="w-3/12 bg-white py-4">
          <Mini/>
          </div>

          </div>



          <div>
          <Footer/>
          </div>
        </div>  
       </body>
    </html>
  )
}
